
# Operation Mode
spring:
  profiles:
    active: prod

  # RedisDB Setting
  redis:
    host: 192.168.2.131
    port: 6379
    password: 1234

  # Spring Session Setting
  session:
    store-type: redis
    redis:
      flush-mode: on_save

# Server Setting
server:
  port: 25000

  # Session Time(sec)
  servlet:
    session:
      timeout: 600


